// RootLayoutServer.tsx
import type { Metadata } from "next";
import { Cormorant_Garamond, Montserrat } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nextgen Schools",
  description: "Generated by create next app",
};

// Configure fonts using Next.js font optimization
const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  variable: "--font-cormorant",
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-montserrat",
  display: 'swap',
});

export default function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${cormorantGaramond.variable} ${montserrat.variable}`}>
      <head>
        {/* Font preconnect for better performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* ✅ Google Tag (gtag.js) */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-WHXP5YHDZF"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-WHXP5YHDZF');
            `,
          }}
        />
      </head>
      <body
        className={`${montserrat.className} content-transparent`}
      >

        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KGJ2S772"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>

        {children}
      </body>
    </html>
  );
}
